### ISSUE TITLE
how to use next or done in basic.check()?

### ISSUE THREAD

**Issue by fanuuuu** [http-auth/http-auth#103]
app.use('/explorer', basic.check(), explorer);
basic.check is not terminating the function. It should exit the function if username & password matched

**Comment by AbdOoSaed** [comment]
hi @gevorg 
in the old version we use http-auth like a middleware

```js
const auth = require('http-auth');
const basic = auth.basic({realm: 'Simon Area.'}, function(user, pass, callback) {
  callback(user === 'username' && pass === 'password');
});

app.get('/admin', auth.connect(basic), dashboard);
```

but now I can't find ```auth.connect``` I think it deprecated

please can u help and tell us how to use it as a middleware?

**Comment by AbdOoSaed** [comment]
@fanuuuu u can use my fork until u receive any comment from @gevorg 

`npm install --save https://github.com/AbdOoSaed/http-auth`

**Comment by gevorg** [comment]
@fanuuuu @AbdOoSaed please check https://github.com/http-auth/http-auth-connect dependency with connect is out from http-auth.
