### ISSUE TITLE
Add ability to pass users array if file is not specified.

### ISSUE THREAD

**Issue by shees-usman** [http-auth/http-auth#106]
There currently doesnt seem to be the ability to pass users array into the config. I had a file which has a custom format so I decided to parse the user credentials manually from the file and pass them in directly as an array in options. But that did not work. I look into the code for base and found the lines:

    this.options = options;
    this.checker = checker;

    // Loading users from file, if file is set.
    this.options.users = [];

    if (!checker && options.file) {
      this.loadUsers();
    }
I think the problem is that the options.users array is cleared even if the file isn't added as a configuration option. I think it should be made a part of the if block to allow passing in a users array.

Please let me know if this makes sense to you or if anything Im doing is incorrect?

**Comment by gevorg** [comment]
@shees-usman thanks for suggestion, currently `htpasswd`, `htdigest` formats are the only ones supported to pass in credentials. In case of custom authentication you can implement any strategy using abstraction layer provided. 
Not sure if I want to extend library with additional configuration for specific case.
