### ISSUE TITLE
Usage of @node-rs/bcrypt results in crash when webpack is used

### ISSUE THREAD

**Issue by MorganLindqvist** [http-auth/http-auth#110]
Hi,

I, as many others, are using [webpack](https://github.com/webpack/webpack) to prepare node applicatitons for distribution.

The issue is that @node-rs is loading modules in a novel way and it is [breaking webpack](https://github.com/webpack/webpack/issues/13053). There is a tiny example triggering the bug in this  link.

The [solution](https://stackoverflow.com/questions/66935848/nodejs-app-with-http-auth-crashes-after-webpack5) identified by Joshua Bigler is to revert back http-auth to version 4.1.2. This version uses another implementation of bcrypt that is compatible with webpack (and yarn).

Could you revert back to this implementation of bcrypt so that we can use the latest and greatest version of http-auth? (At least until node-rs is using a more standard way of importing modules, or webpack learned how to cope with the novel way?)

/Morgan

**Comment by gevorg** [comment]
Thank you @MorganLindqvist , would it be possible to drop a PR for change and I will publish within a day?

**Comment by MorganLindqvist** [comment]
I will try to create the PR this weekend, thanks for your support @gevorg !

**Comment by MorganLindqvist** [comment]
@gevorg, PR created
