### ISSUE TITLE
protecting only some URLs?

### ISSUE THREAD

**Issue by dcsan** [http-auth/http-auth#55]
this is a great way to get an app quickly password protected.

But is there a way to use this to only protect *some* parts of the app?
eg we have an admin area we want locked down, but the rest of the app open to the public.

Alternatively could I create a proxy server that can add the needed auth headers, and proxy requests to an API that *is* protected by this?

tx

**Comment by gevorg** [comment]
Thank you, 

For specific path you can look this snippet:
https://gist.github.com/gevorg/7168d5f02c1ca5362b2a

For proxy authentication you can look this snippet:
https://gist.github.com/gevorg/7918633

Hope it helps, let me know if it is not.

**Comment by dcsan** [comment]
thanks very much, this fixed it really quickly!! :smile_cat:

**Comment by dcsan** [comment]
you might want to add this to the docs...

**Comment by dcsan** [comment]
i made a PR for this ...

**Comment by gevorg** [comment]
Sure, that would be great.. can't see PR so far.
