### ISSUE TITLE
slowdown?

### ISSUE THREAD

**Issue by dcsan** [http-auth/http-auth#58]
we were using this package on a site, but noticed huge slowdowns of 60s or more on various URLs.
is there some known problem with it perhaps? using:

    "http-auth": "^2.2.9",

we had a setup where webpages opened by the user
also used XHR ajax requests to load data. these were what were slowing down.
i assume they have the same auth headers added as they are part of the same browser session?

**Comment by gevorg** [comment]
None that I am aware of. Sure that is something that browser handles for you.
