### ISSUE TITLE
Exposing req object in custom auth function

### ISSUE THREAD

**Issue by jyounus** [http-auth/http-auth#59]
Hey there,

Any chance you could expose the req object in the custom authenticate function? Currently I define the function as: function(username, password, callback).

It would be great if you could change it to: function(username, password, callback, req). This shouldn't break any previous versions.

The reason why I need access to the req object is because req.user being a string isn't good enough for my implementation. I need req.user to be a custom object. So whenever I enable skipUser in the config, I'd like to be able to manually define what req.user should be.

Is this something you could implement please? Or if I tried it myself (I've never used coffee script before), would you consider to merge it in?

Thanks

**Comment by jyounus** [comment]
An alternative would be to check what is being passed back into the callback. If it's a custom object, it should use that for req.user, instead of the default username string which it uses right now. If it's true/false, just continue with how you've implemented it right now.

**Comment by gevorg** [comment]
Hey,

I was wondering if you could do this after authentication callback processing. 
Something like this:

```
// Authentication module.
var auth = require('http-auth');
var basic = auth.basic({
    realm: "Simon Area.",
    file: __dirname + "/../data/users.htpasswd" // gevorg:gpass, Sarah:testpass ...
});

// Application setup.
var app = express();
app.use(auth.connect(basic));
app.use(function (req, res, next) {
  // After authenticated you have proper req.user (skipped or not)
  // Fill free to change it anyway you want
  ...
  // Do forget to call next.
  next();
});

// Setup route.
app.get('/', function(req, res){
  res.send("Hello from express - " + req.user + "!");
});

```

Or if you don't use express you can organize it with native node.js http module as well, just after authentication already is processed. Will it work for you?

**Comment by jyounus** [comment]
I'm using Express, yeah. But I only need this for 1 specific route, not throughout the whole API. This is what my specific router currently looks like:

```
var router = express.Router();

    var basic = Auth.basic({
        realm: "Secure area",
        skipUser: true
    }, basicAuth);

    router.post("/authenticate_session", Auth.connect(basic), doAuthenticate);

    app.use("/api/v1", router);
```

Can I modify your above code to work specifically just for the router object?

**Comment by gevorg** [comment]
Great! Then I think you can use routing mechanism that expressjs provides:

```
var cb0 = function (req, res, next) {
  console.log('CB0');
  next();
}

var cb1 = function (req, res, next) {
  console.log('CB1');
  next();
}

app.get('/example/d', [cb0, cb1], function (req, res, next) {
  console.log('the response will be sent by the next function ...');
  next();
}, function (req, res) {
  res.send('Hello from D!');
});
```

instead of cb1 use Auth.connect(basic) and instead of cb2 use something like this:

```
function (req, res, next) {
  // After authenticated you have proper req.user (skipped or not)
  // Fill free to change it anyway you want
  // e.g. req.user = {'some': 'superObject', 'that': 'youNeed'};
  ...
  // Do not forget to call next.
  next();
}
```

Does it help?

**Comment by jyounus** [comment]
Ah okay, I didn't know I could pass in an array for the second parameter! Good to know! 

However, I still have a problem. I'm not strictly using basic auth, I'm using a slightly modified version of it to suit my project's needs. The username/password are custom tokens that mean something to my backend. I do quite a bit of custom logic inside the Auth.connect(basic) function that gets called. I need both the username and password to reconstruct everything.

But that would mean I would be calling the same logic twice for no real reason, which isn't ideal for me to be honest. I do quite a bit of hashing/decrypting inside of it. 

It would be better for me if either the callback() accepted a custom object OR if the custom authenticate function was expanded to include the req object.

**Comment by gevorg** [comment]
Well...In that case I would recommend you to use something like [passportjs](https://github.com/jaredhanson/passport). http-auth does http basic/digest authentication not more or less.

**Comment by jyounus** [comment]
Ok, thanks anyway.

**Comment by SamDecrock** [comment]
To have access to the original 'calculation' (in my case a database access), I do it like this:

```js
global.auth = function (req, res, next) {
	var realUser = null;

	var basic = auth.basic({
		realm: 'server'
	}, (username, password, callback) => {
		db.users.findOne({username: username}, (err, user) => {
			if(err) return callback(err);
			var passwordHash = crypto.createHash('md5').update(user.salt + password).digest('hex');
			realUser = user;
			return callback(passwordHash == user.password);
		});
	});

	var basicAuth = auth.connect(basic);

	basicAuth(req, res, (err) => {
		if(err) return next(err);
		req.user = realUser;
		next();
	});
}
```

Then use the `auth` function like this:
```js
router.get('/', auth, function (req, res, next) {
	res.render('deviceoverview', { title: 'Device Overview' });
});
```

**Comment by SamDecrock** [comment]
In 6f988b921f019056d8c7850117f88194ce087f48 a custom user object was added. If anyone is looking, it can be used like this:

```js

var basic = auth.basic({
  realm: 'Simon Area'
}, (username, password, callback) => {

  // check your authorization and store the boolean in isAuthorized

  // fetch your custom user object as customUser

  // call the callback like this:
  callback(isAuthorized, customUser);

  // req.user will now contain customUser
});
```
