### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by huseyinkozan** [http-auth/http-auth#66]
Hello,

How can we implement logout ?

**Comment by huseyinkozan** [comment]
It seems hard to implement:
http://stackoverflow.com/questions/233507/how-to-log-out-user-from-web-site-using-basic-authentication
Closing.

**Comment by gevorg** [comment]
Hi, not that it is hard, but is logically impossible from server side, because http authentication is **stateless**. The only option for logout is clearing **authorization** header info from client, sure if you have control over it as browsers don't provide that option.

**Comment by gevorg** [comment]
And btw this looks like good solution:

> Have the user click on a link to https://log:out@example.com/. That will overwrite existing credentials with invalid ones; logging them out.
