### ISSUE TITLE
hapi.js REST framework example

### ISSUE THREAD

**Issue by danactive** [http-auth/http-auth#68]
I'm integrating your module into hapi, would you like an example improve this module's documentation?

-=Dan=-

**Comment by gevorg** [comment]
Sure, sounds good, thank you!

**Comment by gevorg** [comment]
I added proper integration as a separate module here https://github.com/http-auth/http-auth-hapi, please look and let me know if you want to change something there, thank you for your input.

**Comment by danactive** [comment]
@gevorg I was planning to update the hapi sample module, but it is missing.

**Comment by gevorg** [comment]
@danactive I moved integration into the http-auth module https://github.com/http-auth/http-auth/blob/master/src/server/hapi.js
