### ISSUE TITLE
Does http-auth emit any events?

### ISSUE THREAD

**Issue by sisou** [http-auth/http-auth#69]
Hi there!

I just found this awesome and simple package, but I would like to log failed and successful authentication attempts in a security log, and as such was wondering which, if any, events the authentication does emit?

I am using basic auth with a htpasswd file.

Thanks!

**Comment by sisou** [comment]
I managed to get the event when a successfull login happens, because I just emit the event myself as the first thing in the route handling function.

But I also need to log unsuccessful login attempts. How would I recognize those?

**Comment by gevorg** [comment]
Hi, thanks,

My bad, it does not emit any events now, however it is very easy to add ones, by modifying `base.js` file:

    check(req, res, callback) {
        let self = this;
        this.isAuthenticated(req, function (result) {
            if (result instanceof Error) {
                // System error.
                if (callback) {
                    callback.apply(self, [req, res, result]);
                }
            } else if (!result.user) {
                // Failed authentication.
                self.ask(res, result);
            } else {
                // Success.
                if (!this.options.skipUser) {
                    req.user = result.user;
                }

                if (callback) {
                    callback.apply(self, [req, res]);
                }
            }
        });
    }

What I would suggest is to filter http access log instead:

 - `401` status should be failed authentication
 - `20x` statuses success
 - `50x` errors

**Comment by gevorg** [comment]
`unsuccessful login attempts` basically these are all `401` requests (`else if` segment in function).

**Comment by sisou** [comment]
Ok, I made the Base class inherit events.EventEmitter and I can successfully emit `error`, `failed` and `success` events in the respective brackets of the if-else condition you mentioned above.

I will send a PR to show it in a few minutes.

**Comment by sisou** [comment]
OK. I have no experience with ES6 yet and as such was totally lost seeing that the built files that I get in my node_modules directory look different from the src files in the repository. So I will just tell you what I did in the built file `base.js`:

In the top, I added the `_util` and `_EventEmitter` dependency. Those come from node.js directly:
```
var _fs2 = _interopRequireDefault(_fs);

var _util = require("util");

var _EventEmitter = require("events").EventEmitter;

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

Then, in the constructor, I added this:
```
    // Constructor.
    function Base(options, checker) {
        _classCallCheck(this, Base);

        _EventEmitter.call(this);
```

Next, in the `check` function I added the event emitting:
```
        key: "check",
        value: function check(req, res, callback) {
            var self = this;
            this.isAuthenticated(req, function (result) {
                if (result instanceof Error) {
                    self.emit("http-auth.error", req, result);
                    if (callback) {
                        callback.apply(self, [req, res, result]);
                    }
                } else if (!result.user) {
                    self.emit("http-auth.failed", req);
                    self.ask(res, result);
                } else {
                    self.emit("http-auth.success", req);
                    if (!this.options.skipUser) {
                        req.user = result.user;
                    }

                    if (callback) {
                        callback.apply(self, [req, res]);
                    }
                }
            });
        }
```

Finally, I made the `Base` class inherit `_EventEmitter`'s functions:
```
    _util.inherits(Base, _EventEmitter);

    return Base;
```

Hope this helps you somehow :D

**Comment by gevorg** [comment]
I just published events with newer version to NPM, check https://github.com/http-auth/http-auth/blob/master/examples/emitter.js for more info.

**Comment by sisou** [comment]
Wow... I am speechless. That was quick! Is there anyway to donate to the project/you?

**Comment by gevorg** [comment]
Hope it helps, I see you starred the repository on GitHub, thank you :+1:
