### ISSUE TITLE
Protecting specific path witn net

### ISSUE THREAD

**Issue by RedToor** [http-auth/http-auth#73]
how to?

**Comment by gevorg** [comment]
It is possible to do it with express or any other connect based frameworks, for other frameworks you should write some custom code based on routing mechanism that framework provides:

```
// Authentication module.
var auth = require('http-auth');
var basic = auth.basic({
	realm: "Simon Area.",
	file: __dirname + "/../data/users.htpasswd" // gevorg:gpass, Sarah:testpass ...
});

// Application setup.
var app = express();
app.use(function(req, res, next) {
    if ('/specific/path' === req.path) {
        next();
    } else {
    	(auth.connect(basic))(req, res, next);
    }
});
```

https://gist.github.com/gevorg/7168d5f02c1ca5362b2a

**Comment by RedToor** [comment]
> function requestHandler(req, res) {
    var
    fileName = path.basename(req.url) || 'index.html',
    ext = path.extname(fileName),
    localFolder = __dirname + '/public/',
    page404 = localFolder + '404.html';
    if(!extensions[ext]){res.writeHead(404, {'Content-Type': 'text/html'});res.end("");};
    getFile((localFolder + fileName),res,page404,extensions[ext]);
};
http.createServer(basic, requestHandler).listen(WEBPORT);


my code

**Comment by gevorg** [comment]
Unfortunately I don't have snippet for basic HTTP server :(
So you must search for a solution yourself, by reusing my sample.

**Comment by RedToor** [comment]
Ok, thank so much.

**Comment by gevorg** [comment]
Hope this helps https://gist.github.com/gevorg/36362847c559e627ec26f5680a924976

```
// HTTP module
var http = require('http');

// Authentication module.
var auth = require('http-auth');
var basic = auth.basic({
	realm: "Simon Area.",
	file: __dirname + "/../data/users.htpasswd" // gevorg:gpass, Sarah:testpass
});

// Creating new HTTP server.
http.createServer(function(req, res) {
	if (req.url.startsWith('/specific/path')) {
		// Open for connections
		res.end("Public path!");
	} else {
		(auth.connect(basic))(req, res, function() {
			res.end("Welcome to private area - " + req.user + "!");
		});
	}
}).listen(1337, function () {
	// Log URL.
	console.log("Server running at http://127.0.0.1:1337/");
});

```

**Comment by RedToor** [comment]
you save my life!!!!!!!
