### ISSUE TITLE
http-auth does not support htpasswd bcrypt encryption

### ISSUE THREAD

**Issue by sebflipper** [http-auth/http-auth#74]
## Steps to reproduce

1 Generate a new user and password using `htpasswd` using the `-B` flag to use bcrypt encryption:

> htpasswd
> -B  Force bcrypt encryption of the password (very secure).

2 Setup app to use `http-auth` and the generated `htpasswd` file.

3 Try logging into the app with the correct username and password

4 Application responds with an incorrect username or password error

> - `algorithm` - Algorithm that will be used only for **digest** access authentication.
>   - **MD5** by default.
>   - **MD5-sess** can be set.

**Comment by gevorg** [comment]
Do you use digest access authentication or basic ?

**Comment by sebflipper** [comment]
Try using this sample:

`htpasswd -Bc users.htpasswd user` vs. `htpasswd -c users.htpasswd user` with the following code.

Note: the `-B` for `bcrypt` encryption

```
npm install express
npm install http-auth
```

```js
var express = require('express');
// Authentication module.
var auth = require('http-auth');
var basic = auth.basic({
    realm: "Simon Area.",
    file: __dirname + "/users.htpasswd"
});

// Application setup.
var app = express();
app.use(auth.connect(basic));

// Setup route.
app.get('/', (req, res) => {
    res.send(`Hello from express - ${req.user}!`);
});
```

**Comment by gevorg** [comment]
Hah, got it, thanks for reporting, unfortunately Bcrypt is support is not there yet.

**Comment by gevorg** [comment]
@sebflipper I just added Bcrypt support with 3.1.0 version and published to npm. Could you please check it and let me know if there are any problems? Thanks in advance!

**Comment by sebflipper** [comment]
👍  it's now working for me with bcrypt encryption in my `.htpasswd` password file

**Comment by sebflipper** [comment]
@gevorg 👍  it's now working for me with bcrypt encryption in my `.htpasswd` password file

**Comment by mmc41** [comment]
Can Bcrypt be used for digest auth custom (non-file) auth as well?

**Comment by gevorg** [comment]
I don't think so, as you receive only md5 hash on server side.
