### ISSUE TITLE
engine field appears overly restrictive

### ISSUE THREAD

**Issue by sam-github** [http-auth/http-auth#75]
Luckily, its ignored by npm (by default), but it breaks with yarn (by default).

What about this module doesn't work when run on current LTS node versions, like 4.x? Why is it claiming `^>=6.7` as the node requirement?

It installs and tests pass on recent node 4.x.

/cc @bajtos, I think this is a loopback/express dep.

**Comment by gevorg** [comment]
True, thanks for hint. 

Changed to `"node": ">=4.6.1"`.

**Comment by sam-github** [comment]
Thank you very much!

**Comment by sam-github** [comment]
And you republished apache-crypt and -md5, too, it looks like, great! I was about to open more issues for your deps.
