### ISSUE TITLE
apache-md5 and apache-crypto

### ISSUE THREAD

**Issue by develmts** [http-auth/http-auth#76]
Can somebody detail the reason for using apache-md5 and apache-crypt instead of the standard node crypto.hash()  functions?

Is there any compatibility issue against the RFC HTTP Digest using one or the other ?

**Comment by gevorg** [comment]
[apache-md5](https://github.com/http-auth/apache-md5) and [apache-crypt](https://github.com/http-auth/apache-crypt) are used for compatibility reasons with [htpasswd](https://github.com/http-auth/htpasswd/) utility **ONLY** for Basic Access Authentication.

Digest Access Authentication [is not using those libraries anyhow](https://github.com/http-auth/http-auth/blob/master/src/auth/digest.js).

**Comment by develmts** [comment]
OK. thanks

So then , maybe splitting module would make sense for those of us that only require digest auth  and ( like me) are used to work with a small as possible dependency tree

**Comment by gevorg** [comment]
I will leave it like this, as it is simpler from usage perspective.

**Comment by develmts** [comment]
ok. no problem, just an idea
