### ISSUE TITLE
How can i add basic auth to a middleware?

### ISSUE THREAD

**Issue by madnight** [http-auth/http-auth#77]
I use this middleware https://github.com/jochen-schweizer/express-prom-bundle
it exposes the url /metrics after adding: `app.use(metricsMiddleware);`

How could i protect /metrics or any other middleware path.

**Comment by gevorg** [comment]
Look express integration part https://github.com/http-auth/http-auth#express-framework-integration

To protect all urls just add `app.use(auth.connect(basic));` before `app.use(metricsMiddleware);` and if you need to have some conditional checks for urls, you can use following snippet

```javascript
app.use(function(req, res, next) {
    if ('/specific/path' === req.path) {
        next();
    } else {
    	(auth.connect(basic))(req, res, next);
    }
});

```
