### ISSUE TITLE
Use constant-time string comparisons

### ISSUE THREAD

**Issue by cmc333333** [http-auth/http-auth#78]
At multiple points in this library, password strings are being compared using `===`. Unfortunately, such an operation short-circuits when characters don't match. Put differently, the longer your guessed password matches the real password, the more time the computation will take. Unfortunately, this is measurable by an attacker -- see [this overview](https://codahale.com/a-lesson-in-timing-attacks/) for more.

Please swap out all of the string comparisons with a constant-time comparison library.

**Comment by gevorg** [comment]
Thanks for letting me know, I guess it is more safe now :)
