### ISSUE TITLE
Amazon Application Load Balancer - 504 Gateway TImeout

### ISSUE THREAD

**Issue by valeeum** [http-auth/http-auth#82]
Any idea why I'd be getting a 504 gateway timeout after providing the prompt with my user and pass info?  All subsequent requests also timeout.  I'm currently using this on AWS Elastic Beanstalk behind an Application Load Balancer.  Everything works as expected on my local dev environment.

**Comment by gevorg** [comment]
The first thing I would do is checking http headers that server/client received.

**Comment by gevorg** [comment]
@valeeum  I think my comment could be misunderstood, basically I was suggesting you to look into headers and post here the results.

**Comment by valeeum** [comment]
@gevorg thanks for the feedback.  it was actually an issue which is unrelated to this module.  I will close this out.  thanks!
