### ISSUE TITLE
Unable to get digest auth to work like in example

### ISSUE THREAD

**Issue by mmc41** [http-auth/http-auth#83]
I am trying to use http-auth to get custom (non-file based) digest auth to work between chrome/firefox and hapi+http-auth. I have modelled my code after the digest_nofile.js example but I can't get it to work with a browser client (firefox or chome). My custom function get's called but the hash I compute (like in the example) gets rejected. Both if I specify  qop: 'none' and  qop: 'auth' in the settings object.

Also, I don't understand the claim of the example that the hash should be simply be computed as md5(username:realm:password) to be passed to the callback - what about the nonce and cnonce etc mentioned in the wiki about digest auth (https://en.wikipedia.org/wiki/Digest_access_authentication)?

**Comment by gevorg** [comment]
md5(username:realm:password) is just part of Digest authentication standard https://tools.ietf.org/html/rfc2617, you can change it anyhow, however the result will be your custom standard and you cannot call it Digest anymore.
