### ISSUE TITLE
Exclude a given network or IP from authentication

### ISSUE THREAD

**Issue by privatesam** [http-auth/http-auth#84]
Thanks for this module.  I'm playing around with a few things and wondered if there was any way of excluding an IP or range from needing to authenticate, i.e. the internal LAN.  With Nginx you can declare something like this:

    allow 192.168.0.0/24;
    deny all;
    auth_basic "Restricted Content";
    auth_basic_user_file /etc/nginx/.htpasswd;

Thanks in advance for any help.

**Comment by gevorg** [comment]
No, you cannot do it with http-auth.
