### ISSUE TITLE
hapi 17 support

### ISSUE THREAD

**Issue by matcho** [http-auth/http-auth#85]
Hi,

Do you plan to make `http-auth` compatible with hapi 17, that is async / await compatible ?

It's particularly useful for authentication users via *htpasswd* file, which [hapi-auth-basic](https://github.com/hapijs/hapi-auth-basic) does not seem to support.

Thanks

**Comment by gevorg** [comment]
Hi,

Not in near future, however something like https://github.com/http-auth/http-auth-koa would be good addition. Gevorg
