### ISSUE TITLE
(express) Doesn't work with static content

### ISSUE THREAD

**Issue by daintycode** [http-auth/http-auth#86]
```
webServer.use(express.static(`${__dirname}/static`));
webServer.use(auth.connect(basicAuth));
```

Won't secure any data served from `static/`. Any other routes are secured.

Specifically I'd like to secure a route in there. so `/` is accessible, but e.g. `/staff/` needs http-auth.

**Comment by gevorg** [comment]
Try in reverse order:

```
webServer.use(auth.connect(basicAuth));
webServer.use(express.static(`${__dirname}/static`));
