### ISSUE TITLE
Digest not working

### ISSUE THREAD

**Issue by JaapWeijland** [http-auth/http-auth#90]
This is my code:

```
const digest= auth.digest({
    realm: "pdfmodule",
    file: __dirname + "/users.htdigest"
});

app.get('/generate', auth.connect(digest), async (req, res) => { ... });
```

My `users.htdigest` file:

```
admin:pdfmodule:47bce5c74f589f4867dbd57e9ca9f808
```

The hash is equal to MD5(aaa).

I try to access /generate. My browser pops up an authentication screen. I type admin as username, and aaa as password. I cannot get in.

What is going wrong here? Basic auth works, if I delete the realm and switch to auth.basic. Digest doesn't work, however. I'm using Chrome 69.

**Comment by gevorg** [comment]
MD5
"$apr1$" + the result of an Apache-specific algorithm using an iterated (1,000 times) MD5 digest of various combinations of a random 32-bit salt and the password. See the APR source file apr_md5.c for the details of the algorithm.

https://httpd.apache.org/docs/2.4/misc/password_encryptions.html
