### ISSUE TITLE
Add documentation for digest usage

### ISSUE THREAD

**Issue by EvanDarwin** [http-auth/http-auth#91]
There's a severe lack of information in the readme about how to use `auth.digest`, and considering the callback signature is different it's very confusing. Could more info be provided in the docs?

**Comment by adiroiban** [comment]
Here is my take on this

```
const auth = require('http-auth');
const auth_method = auth.digest({
    realm: 'assistant-relay',
    file: __dirname + '/path/to/your/users.htpasswd'
});

const app = express();
// http-auth should be the first middleware to use.
app.use(auth.connect(auth_method));
```

Then in `users.htpasswd` store the **HA1** hash.
The documentation is wrong about `passHash` as this is not the password hash but the hash of `HA1 = MD5(username:realm:password)`

I will try to submit a PR for this :)

**Comment by EvanDarwin** [comment]
@adiroiban And what if I don't want to use an `.htpasswd` file?

**Comment by gevorg** [comment]
btw extension for digest authentication is not .htpasswd, but .htdigest :)

**Comment by adiroiban** [comment]
The current API only has the local file path option.
there is no option to pass a stream or delegate to other function.

@gevorg thanks :) good point :)
