### ISSUE TITLE
Koa@Next example not working

### ISSUE THREAD

**Issue by BananaAcid** [http-auth/http-auth#93]
having the imports, a valid htpasswd and its path testet, basic set like in the example, using koa next ...
`app.use(koaAuth(basic));` results in 
```
TypeError: koaAuth is not a function
    at file:///mnt/.........../server.mjs:114:13
    at Generator.next (<anonymous>)
```

**Comment by gevorg** [comment]
did you import `import koaAuth from 'http-auth-koa'` ? please share full sample.

**Comment by BananaAcid** [comment]
What ever that situation was, i ended up with [this](https://github.com/BananaAcid/node-file-manager-esm/blob/master/bin/node-file-manager-esm.mjs#L119-L142).

**Comment by MartinWickman** [comment]
It fails because Koa requires `next()` to be `await next()`. This can result in really weird errors. In @BananaAcid 's case I belive it will always continue running the next middleware, which is probably not what is intended.

The only way I could make it work is by:

```
 return async (ctx, next) => {
            digest.check(ctx.req, ctx.res, (req, res, err) => {
                if (err) {
                    throw err;
                } else {
                    console.log ("check passed");
                    //await next() doesn't work here since callback is not called async
                }
            });

            // hack to check if we passed or not
            if (ctx.req.user) { 
                console.log ('next()');
                await next();
            } else {
                console.log ('No user. digest failed');
            }
        }
```

**Comment by gevorg** [comment]
Would be great to have PR for this @MartinWickman @BananaAcid do you think it is possible?

**Comment by BananaAcid** [comment]
Well - we created workarounds using the internal functions (actually recreating the plugins behavior) - this does not qualify as a PR.

**Comment by gevorg** [comment]
Koa integration removed, please check https://github.com/http-auth/http-auth-koa
