### ISSUE TITLE
Replay is possible in digest notification

### ISSUE THREAD

**Issue by dukei** [http-auth/http-auth#94]
https://github.com/http-auth/http-auth/blob/0896bab1aae03d04d9df859575e485fb1a952c5d/src/auth/digest.js#L159

If a client specifies large nonceCount then this request can be replayed `(nonceCount - serverNonce[2])` times. This line should be changed to 
```javascript
serverNonce[2] = nc
```

Moreover request counter should be hexadecimal.

**Comment by gevorg** [comment]
@dukei thanks for PR and issue, will merge it tonight.

**Comment by gevorg** [comment]
published with `3.2.4` version.
