### ISSUE TITLE
auth-scheme is supposed to be case-insensitive per RFC

### ISSUE THREAD

**Issue by srguiwiz** [http-auth/http-auth#96]
RFC 2617 reads "uses an extensible, case-insensitive token to identify the authentication scheme".

In `basic.js` and `digest.js`, there are case sensitive tests `=== "Basic"` and `=== "Digest"`.

If you agree I can submit a pull request defining one time

```
const basicSchemeRegExp = /^basic$/i;
```

and then using

```
if (basicSchemeRegExp.test(tokens[0])) {
```

or you can do it.

**Comment by gevorg** [comment]
Thanks.
