### ISSUE TITLE
Expressjs auth.connect does not work anymore

### ISSUE THREAD

**Issue by velizarn** [http-auth/http-auth#98]
Expressjs middleware ends with an error message:

`TypeError: auth.connect is not a function`

it seems _connect_ method has been removed from version 4.

Is there a v4 workaround for Expressjs?

**Comment by gevorg** [comment]
@velizarn sorry for incontinence I moved it to separate package: https://github.com/http-auth/http-auth-connect

**Comment by velizarn** [comment]
@gevorg thanks for your help. Unfortunately importing _http-auth-connect_ module doesn't solve the issue. I'm using expressjs with clustering, not sure if this is causing the issue. 
Downgrading to version 3.2.4 => no issues.

**Comment by gevorg** [comment]
It is just simple connect middleware, should not cause problems, can you share code fragment?

**Comment by velizarn** [comment]
@gevorg its similar to this one (its not the same script):
https://github.com/velizarn/node-heroku-http-auth/blob/master/index.js
I replaced _.use(auth.connect(basic))_ with _.use(authConnect(basic))_
it seems the middleware doesn't hit next(). when I try to load my protected page the browser doesn't show anything.

**Comment by gevorg** [comment]
@velizarn re-published, please re-check looks like I was using old version http-auth in dev dependencies.

**Comment by velizarn** [comment]
@gevorg after the update it works ok. Thanks!

**Comment by gevorg** [comment]
glad it worked, sorry for trouble and thanks for reporting.

**Comment by ghostganz** [comment]
It would help if there were **some** documentation or release notes about the breaking changes in 4.x...

**Comment by gevorg** [comment]
> It would help if there were **some** documentation or release notes about the breaking changes in 4.x...

Point taken related to release notes, but for usage of latest version just check readme.md and examples directory, both are updated.
